services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/hackathons-canada/hackathons_canada:latest
    command: /scripts/django/start
    ports:
      - "22300:22300"
    volumes:
      - ${PWD}/hackathons_canada/local_settings.py:/app/hackathons_canada/local_settings.py:ro
      - /srv/static:/app/static2
      - /srv/media:/app/media
      - ./logs/:/logs/
    depends_on:
      - valkey
    env_file:
      - .env
    restart: unless-stopped

  valkey:
    image: "valkey/valkey:8-alpine"
    restart: always
    environment:
      - VALKEY_EXTRA_FLAGS='--save 60 1 --loglevel warning'
    volumes:
      - cache-data:/data

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/hackathons-canada/hackathons_canada:latest
    command: /scripts/celery/worker/start
    volumes:
      - .:/app
      - ./logs/:/logs/
    env_file:
      - .env
    depends_on:
      - valkey
    healthcheck:
      test:
        ["CMD", "/opt/pysetup/.venv/bin/celery", "worker", "--loglevel=info"]
      interval: 10s
      retries: 5

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/hackathons-canada/hackathons_canada:latest
    command: /scripts/celery/beat/start
    volumes:
      - .:/app
      - ./logs/:/logs/
    env_file:
      - .env
    depends_on:
      - valkey
    healthcheck:
      test: ["CMD", "/opt/pysetup/.venv/bin/celery", "beat", "--loglevel=info"]
      interval: 10s
      retries: 5

  flower:
    image: ghcr.io/hackathons-canada/hackathons_canada:latest
    command:
      [
        "celery",
        "--broker=redis://valkey:6379",
        "flower",
        "--port=5557",
        "--persisten=True",
      ]
    volumes:
      - flower-data:/data
    env_file:
      - .env
    ports:
      - "5557:5557"
    depends_on:
      - valkey

volumes:
  static_volume:
  media_volume:
  flower-data:
  cache-data:
